/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-117968-g1e3dc705df-20241201"
#endif /* AVUTIL_FFVERSION_H */
